-- Add province field to crm_companies table
ALTER TABLE public.crm_companies ADD COLUMN IF NOT EXISTS province text;

-- Create Italian cities and postal codes table for autocomplete
CREATE TABLE IF NOT EXISTS public.italian_cities (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  province_code text NOT NULL,
  province_name text NOT NULL,
  city_name text NOT NULL,
  postal_code text NOT NULL,
  region text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Add some sample data for major Italian cities and provinces
INSERT INTO public.italian_cities (province_code, province_name, city_name, postal_code, region) VALUES
-- Lombardia
('MI', 'Milano', 'Milano', '20100', 'Lombardia'),
('MI', 'Milano', 'Milano', '20121', 'Lombardia'),
('MI', 'Milano', 'Milano', '20122', 'Lombardia'),
('MI', 'Milano', 'Milano', '20123', 'Lombardia'),
('MI', 'Milano', 'Milano', '20124', 'Lombardia'),
('MI', 'Milano', 'Milano', '20125', 'Lombardia'),
('MI', 'Milano', 'Milano', '20126', 'Lombardia'),
('MI', 'Milano', 'Milano', '20127', 'Lombardia'),
('MI', 'Milano', 'Milano', '20128', 'Lombardia'),
('MI', 'Milano', 'Milano', '20129', 'Lombardia'),
('MI', 'Milano', 'Milano', '20131', 'Lombardia'),
('MI', 'Milano', 'Milano', '20132', 'Lombardia'),
('MI', 'Milano', 'Milano', '20133', 'Lombardia'),
('MI', 'Milano', 'Milano', '20134', 'Lombardia'),
('MI', 'Milano', 'Milano', '20135', 'Lombardia'),
('MI', 'Milano', 'Milano', '20136', 'Lombardia'),
('MI', 'Milano', 'Milano', '20137', 'Lombardia'),
('MI', 'Milano', 'Milano', '20138', 'Lombardia'),
('MI', 'Milano', 'Milano', '20139', 'Lombardia'),
('MI', 'Milano', 'Milano', '20141', 'Lombardia'),
('MI', 'Milano', 'Milano', '20142', 'Lombardia'),
('MI', 'Milano', 'Milano', '20143', 'Lombardia'),
('MI', 'Milano', 'Milano', '20144', 'Lombardia'),
('MI', 'Milano', 'Milano', '20145', 'Lombardia'),
('MI', 'Milano', 'Milano', '20146', 'Lombardia'),
('MI', 'Milano', 'Milano', '20147', 'Lombardia'),
('MI', 'Milano', 'Milano', '20148', 'Lombardia'),
('MI', 'Milano', 'Milano', '20149', 'Lombardia'),
('MI', 'Milano', 'Milano', '20151', 'Lombardia'),
('MI', 'Milano', 'Milano', '20152', 'Lombardia'),
('MI', 'Milano', 'Milano', '20153', 'Lombardia'),
('MI', 'Milano', 'Milano', '20154', 'Lombardia'),
('MI', 'Milano', 'Milano', '20155', 'Lombardia'),
('MI', 'Milano', 'Milano', '20156', 'Lombardia'),
('MI', 'Milano', 'Milano', '20157', 'Lombardia'),
('MI', 'Milano', 'Milano', '20158', 'Lombardia'),
('MI', 'Milano', 'Milano', '20159', 'Lombardia'),
('MI', 'Milano', 'Milano', '20161', 'Lombardia'),
('MI', 'Milano', 'Milano', '20162', 'Lombardia'),
('MI', 'Milano', 'Bergamo', '24100', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24121', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24122', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24123', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24124', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24125', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24126', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24127', 'Lombardia'),
('BG', 'Bergamo', 'Bergamo', '24128', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25100', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25121', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25122', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25123', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25124', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25125', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25126', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25127', 'Lombardia'),
('BS', 'Brescia', 'Brescia', '25128', 'Lombardia'),
('CO', 'Como', 'Como', '22100', 'Lombardia'),

-- Lazio
('RM', 'Roma', 'Roma', '00100', 'Lazio'),
('RM', 'Roma', 'Roma', '00118', 'Lazio'),
('RM', 'Roma', 'Roma', '00119', 'Lazio'),
('RM', 'Roma', 'Roma', '00120', 'Lazio'),
('RM', 'Roma', 'Roma', '00121', 'Lazio'),
('RM', 'Roma', 'Roma', '00122', 'Lazio'),
('RM', 'Roma', 'Roma', '00123', 'Lazio'),
('RM', 'Roma', 'Roma', '00124', 'Lazio'),
('RM', 'Roma', 'Roma', '00125', 'Lazio'),
('RM', 'Roma', 'Roma', '00126', 'Lazio'),
('RM', 'Roma', 'Roma', '00131', 'Lazio'),
('RM', 'Roma', 'Roma', '00132', 'Lazio'),
('RM', 'Roma', 'Roma', '00133', 'Lazio'),
('RM', 'Roma', 'Roma', '00134', 'Lazio'),
('RM', 'Roma', 'Roma', '00135', 'Lazio'),
('RM', 'Roma', 'Roma', '00136', 'Lazio'),
('RM', 'Roma', 'Roma', '00137', 'Lazio'),
('RM', 'Roma', 'Roma', '00138', 'Lazio'),
('RM', 'Roma', 'Roma', '00139', 'Lazio'),
('RM', 'Roma', 'Roma', '00141', 'Lazio'),
('RM', 'Roma', 'Roma', '00142', 'Lazio'),
('RM', 'Roma', 'Roma', '00143', 'Lazio'),
('RM', 'Roma', 'Roma', '00144', 'Lazio'),
('RM', 'Roma', 'Roma', '00145', 'Lazio'),
('RM', 'Roma', 'Roma', '00146', 'Lazio'),
('RM', 'Roma', 'Roma', '00147', 'Lazio'),
('RM', 'Roma', 'Roma', '00148', 'Lazio'),
('RM', 'Roma', 'Roma', '00149', 'Lazio'),
('RM', 'Roma', 'Roma', '00151', 'Lazio'),
('RM', 'Roma', 'Roma', '00152', 'Lazio'),
('RM', 'Roma', 'Roma', '00153', 'Lazio'),
('RM', 'Roma', 'Roma', '00154', 'Lazio'),
('RM', 'Roma', 'Roma', '00155', 'Lazio'),
('RM', 'Roma', 'Roma', '00156', 'Lazio'),
('RM', 'Roma', 'Roma', '00157', 'Lazio'),
('RM', 'Roma', 'Roma', '00158', 'Lazio'),
('RM', 'Roma', 'Roma', '00159', 'Lazio'),
('RM', 'Roma', 'Roma', '00161', 'Lazio'),
('RM', 'Roma', 'Roma', '00162', 'Lazio'),
('RM', 'Roma', 'Roma', '00163', 'Lazio'),
('RM', 'Roma', 'Roma', '00164', 'Lazio'),
('RM', 'Roma', 'Roma', '00165', 'Lazio'),
('RM', 'Roma', 'Roma', '00166', 'Lazio'),
('RM', 'Roma', 'Roma', '00167', 'Lazio'),
('RM', 'Roma', 'Roma', '00168', 'Lazio'),
('RM', 'Roma', 'Roma', '00169', 'Lazio'),
('RM', 'Roma', 'Roma', '00171', 'Lazio'),
('RM', 'Roma', 'Roma', '00172', 'Lazio'),
('RM', 'Roma', 'Roma', '00173', 'Lazio'),
('RM', 'Roma', 'Roma', '00174', 'Lazio'),
('RM', 'Roma', 'Roma', '00175', 'Lazio'),
('RM', 'Roma', 'Roma', '00176', 'Lazio'),
('RM', 'Roma', 'Roma', '00177', 'Lazio'),
('RM', 'Roma', 'Roma', '00178', 'Lazio'),
('RM', 'Roma', 'Roma', '00179', 'Lazio'),
('RM', 'Roma', 'Roma', '00181', 'Lazio'),
('RM', 'Roma', 'Roma', '00182', 'Lazio'),
('RM', 'Roma', 'Roma', '00183', 'Lazio'),
('RM', 'Roma', 'Roma', '00184', 'Lazio'),
('RM', 'Roma', 'Roma', '00185', 'Lazio'),
('RM', 'Roma', 'Roma', '00186', 'Lazio'),
('RM', 'Roma', 'Roma', '00187', 'Lazio'),
('RM', 'Roma', 'Roma', '00188', 'Lazio'),
('RM', 'Roma', 'Roma', '00189', 'Lazio'),
('RM', 'Roma', 'Roma', '00191', 'Lazio'),
('RM', 'Roma', 'Roma', '00192', 'Lazio'),
('RM', 'Roma', 'Roma', '00193', 'Lazio'),
('RM', 'Roma', 'Roma', '00194', 'Lazio'),
('RM', 'Roma', 'Roma', '00195', 'Lazio'),
('RM', 'Roma', 'Roma', '00196', 'Lazio'),
('RM', 'Roma', 'Roma', '00197', 'Lazio'),
('RM', 'Roma', 'Roma', '00198', 'Lazio'),
('RM', 'Roma', 'Roma', '00199', 'Lazio'),

-- Veneto
('VE', 'Venezia', 'Venezia', '30100', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30121', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30122', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30123', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30124', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30125', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30126', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30127', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30128', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30129', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30131', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30132', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30133', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30134', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30135', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30136', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30137', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30138', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30139', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30141', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30142', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30170', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30171', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30172', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30173', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30174', 'Veneto'),
('VE', 'Venezia', 'Venezia', '30175', 'Veneto'),
('VR', 'Verona', 'Verona', '37100', 'Veneto'),
('VR', 'Verona', 'Verona', '37121', 'Veneto'),
('VR', 'Verona', 'Verona', '37122', 'Veneto'),
('VR', 'Verona', 'Verona', '37123', 'Veneto'),
('VR', 'Verona', 'Verona', '37124', 'Veneto'),
('VR', 'Verona', 'Verona', '37125', 'Veneto'),
('VR', 'Verona', 'Verona', '37126', 'Veneto'),
('VR', 'Verona', 'Verona', '37127', 'Veneto'),
('VR', 'Verona', 'Verona', '37128', 'Veneto'),
('VR', 'Verona', 'Verona', '37129', 'Veneto'),
('VR', 'Verona', 'Verona', '37131', 'Veneto'),
('VR', 'Verona', 'Verona', '37132', 'Veneto'),
('VR', 'Verona', 'Verona', '37133', 'Veneto'),
('VR', 'Verona', 'Verona', '37134', 'Veneto'),
('VR', 'Verona', 'Verona', '37135', 'Veneto'),
('VR', 'Verona', 'Verona', '37136', 'Veneto'),
('VR', 'Verona', 'Verona', '37137', 'Veneto'),
('VR', 'Verona', 'Verona', '37138', 'Veneto'),
('VR', 'Verona', 'Verona', '37139', 'Veneto'),
('PD', 'Padova', 'Padova', '35100', 'Veneto'),
('PD', 'Padova', 'Padova', '35121', 'Veneto'),
('PD', 'Padova', 'Padova', '35122', 'Veneto'),
('PD', 'Padova', 'Padova', '35123', 'Veneto'),
('PD', 'Padova', 'Padova', '35124', 'Veneto'),
('PD', 'Padova', 'Padova', '35125', 'Veneto'),
('PD', 'Padova', 'Padova', '35126', 'Veneto'),
('PD', 'Padova', 'Padova', '35127', 'Veneto'),
('PD', 'Padova', 'Padova', '35128', 'Veneto'),
('PD', 'Padova', 'Padova', '35129', 'Veneto'),
('PD', 'Padova', 'Padova', '35131', 'Veneto'),
('PD', 'Padova', 'Padova', '35132', 'Veneto'),
('PD', 'Padova', 'Padova', '35133', 'Veneto'),
('PD', 'Padova', 'Padova', '35134', 'Veneto'),
('PD', 'Padova', 'Padova', '35135', 'Veneto'),
('PD', 'Padova', 'Padova', '35136', 'Veneto'),
('PD', 'Padova', 'Padova', '35137', 'Veneto'),
('PD', 'Padova', 'Padova', '35138', 'Veneto'),
('PD', 'Padova', 'Padova', '35139', 'Veneto'),

-- Piemonte
('TO', 'Torino', 'Torino', '10100', 'Piemonte'),
('TO', 'Torino', 'Torino', '10121', 'Piemonte'),
('TO', 'Torino', 'Torino', '10122', 'Piemonte'),
('TO', 'Torino', 'Torino', '10123', 'Piemonte'),
('TO', 'Torino', 'Torino', '10124', 'Piemonte'),
('TO', 'Torino', 'Torino', '10125', 'Piemonte'),
('TO', 'Torino', 'Torino', '10126', 'Piemonte'),
('TO', 'Torino', 'Torino', '10127', 'Piemonte'),
('TO', 'Torino', 'Torino', '10128', 'Piemonte'),
('TO', 'Torino', 'Torino', '10129', 'Piemonte'),
('TO', 'Torino', 'Torino', '10131', 'Piemonte'),
('TO', 'Torino', 'Torino', '10132', 'Piemonte'),
('TO', 'Torino', 'Torino', '10133', 'Piemonte'),
('TO', 'Torino', 'Torino', '10134', 'Piemonte'),
('TO', 'Torino', 'Torino', '10135', 'Piemonte'),
('TO', 'Torino', 'Torino', '10136', 'Piemonte'),
('TO', 'Torino', 'Torino', '10137', 'Piemonte'),
('TO', 'Torino', 'Torino', '10138', 'Piemonte'),
('TO', 'Torino', 'Torino', '10139', 'Piemonte'),
('TO', 'Torino', 'Torino', '10141', 'Piemonte'),
('TO', 'Torino', 'Torino', '10142', 'Piemonte'),
('TO', 'Torino', 'Torino', '10143', 'Piemonte'),
('TO', 'Torino', 'Torino', '10144', 'Piemonte'),
('TO', 'Torino', 'Torino', '10145', 'Piemonte'),
('TO', 'Torino', 'Torino', '10146', 'Piemonte'),
('TO', 'Torino', 'Torino', '10147', 'Piemonte'),
('TO', 'Torino', 'Torino', '10148', 'Piemonte'),
('TO', 'Torino', 'Torino', '10149', 'Piemonte'),
('TO', 'Torino', 'Torino', '10151', 'Piemonte'),
('TO', 'Torino', 'Torino', '10152', 'Piemonte'),
('TO', 'Torino', 'Torino', '10153', 'Piemonte'),
('TO', 'Torino', 'Torino', '10154', 'Piemonte'),
('TO', 'Torino', 'Torino', '10155', 'Piemonte'),
('TO', 'Torino', 'Torino', '10156', 'Piemonte'),

-- Emilia-Romagna
('BO', 'Bologna', 'Bologna', '40100', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40121', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40122', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40123', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40124', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40125', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40126', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40127', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40128', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40129', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40131', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40132', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40133', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40134', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40135', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40136', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40137', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40138', 'Emilia-Romagna'),
('BO', 'Bologna', 'Bologna', '40139', 'Emilia-Romagna'),

-- Toscana
('FI', 'Firenze', 'Firenze', '50100', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50121', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50122', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50123', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50124', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50125', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50126', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50127', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50128', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50129', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50131', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50132', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50133', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50134', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50135', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50136', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50137', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50138', 'Toscana'),
('FI', 'Firenze', 'Firenze', '50139', 'Toscana'),

-- Campania
('NA', 'Napoli', 'Napoli', '80100', 'Campania'),
('NA', 'Napoli', 'Napoli', '80121', 'Campania'),
('NA', 'Napoli', 'Napoli', '80122', 'Campania'),
('NA', 'Napoli', 'Napoli', '80123', 'Campania'),
('NA', 'Napoli', 'Napoli', '80124', 'Campania'),
('NA', 'Napoli', 'Napoli', '80125', 'Campania'),
('NA', 'Napoli', 'Napoli', '80126', 'Campania'),
('NA', 'Napoli', 'Napoli', '80127', 'Campania'),
('NA', 'Napoli', 'Napoli', '80128', 'Campania'),
('NA', 'Napoli', 'Napoli', '80129', 'Campania'),
('NA', 'Napoli', 'Napoli', '80131', 'Campania'),
('NA', 'Napoli', 'Napoli', '80132', 'Campania'),
('NA', 'Napoli', 'Napoli', '80133', 'Campania'),
('NA', 'Napoli', 'Napoli', '80134', 'Campania'),
('NA', 'Napoli', 'Napoli', '80135', 'Campania'),
('NA', 'Napoli', 'Napoli', '80136', 'Campania'),
('NA', 'Napoli', 'Napoli', '80137', 'Campania'),
('NA', 'Napoli', 'Napoli', '80138', 'Campania'),
('NA', 'Napoli', 'Napoli', '80139', 'Campania'),
('NA', 'Napoli', 'Napoli', '80141', 'Campania'),
('NA', 'Napoli', 'Napoli', '80142', 'Campania'),
('NA', 'Napoli', 'Napoli', '80143', 'Campania'),
('NA', 'Napoli', 'Napoli', '80144', 'Campania'),
('NA', 'Napoli', 'Napoli', '80145', 'Campania'),
('NA', 'Napoli', 'Napoli', '80146', 'Campania'),
('NA', 'Napoli', 'Napoli', '80147', 'Campania');

-- Enable RLS on italian_cities table
ALTER TABLE public.italian_cities ENABLE ROW LEVEL SECURITY;

-- Create RLS policy for italian_cities (read-only for authenticated users)
CREATE POLICY "Users can view Italian cities data" ON public.italian_cities
FOR SELECT TO authenticated
USING (true);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_italian_cities_province_code ON public.italian_cities(province_code);
CREATE INDEX IF NOT EXISTS idx_italian_cities_city_name ON public.italian_cities(city_name);
CREATE INDEX IF NOT EXISTS idx_italian_cities_postal_code ON public.italian_cities(postal_code);